"""Verify an isolated environment and manage the hashed dependency lock."""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEV_LOCK_SOURCE = ROOT / "requirements-dev.txt"
RUNTIME_LOCK_SOURCE = ROOT / "requirements.txt"
RUNTIME_LOCK = ROOT / "requirements-runtime.lock.txt"
CONSTRAINTS = ROOT / "constraints.txt"


def in_virtualenv() -> bool:
    return sys.prefix != getattr(sys, "base_prefix", sys.prefix)


def run_pip_check() -> int:
    return subprocess.run([sys.executable, "-m", "pip", "check"], cwd=ROOT).returncode


def _inside_root(path: Path) -> bool:
    try:
        path.resolve().relative_to(ROOT.resolve())
        return True
    except ValueError:
        return False


def write_lockfile(path: Path, source: Path = DEV_LOCK_SOURCE) -> None:
    """Resolve a universal, fully pinned lockfile with artifact hashes."""
    if not _inside_root(path):
        raise ValueError(f"Lockfile must stay inside the project root: {path}")
    uv = shutil.which("uv")
    if not uv:
        raise RuntimeError("uv is required to regenerate the lockfile: https://docs.astral.sh/uv/")
    subprocess.run(
        [
            uv,
            "pip",
            "compile",
            str(source),
            "--constraint",
            str(CONSTRAINTS),
            "--universal",
            "--generate-hashes",
            "--output-file",
            str(path),
        ],
        cwd=ROOT,
        check=True,
    )
    _normalize_lockfile_header(path, source)


def _normalize_lockfile_header(path: Path, source: Path) -> None:
    """Remove local absolute paths emitted by uv from a portable lock header."""
    lines = path.read_text(encoding="utf-8").splitlines()
    if len(lines) >= 2 and lines[0].startswith("# This file was autogenerated by uv") and lines[1].startswith("#    uv pip compile "):
        lines[:2] = [
            "# This file was autogenerated by uv.",
            f"# Source: {source.name}; constraint: {CONSTRAINTS.name}; universal hashes enabled.",
        ]
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def verify_hashed_lock(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    if "--hash=sha256:" not in text:
        raise ValueError(f"Lockfile does not contain package hashes: {path}")
    if any(line.startswith("-e ") for line in text.splitlines()):
        raise ValueError("Editable requirements are not permitted in the release lockfile")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-lock", type=Path, help="Resolve a universal hash-locked requirements file with uv.")
    parser.add_argument("--write-runtime-lock", action="store_true", help="Resolve the runtime-only hash lock from requirements.txt.")
    parser.add_argument("--verify-lock", type=Path, help="Verify that a lockfile contains hashes and no editable installs.")
    parser.add_argument("--allow-system", action="store_true", help="Allow checks outside a virtualenv.")
    args = parser.parse_args()

    if not in_virtualenv() and not args.allow_system:
        print("Not running inside a virtualenv. Create one first, then rerun this script.")
        return 2

    pip_status = run_pip_check()
    if pip_status != 0:
        return pip_status

    if args.write_lock and args.write_runtime_lock:
        parser.error("Use either --write-lock or --write-runtime-lock, not both")
    if args.write_lock:
        lock_path = args.write_lock if args.write_lock.is_absolute() else ROOT / args.write_lock
        write_lockfile(lock_path)
        print(f"Wrote lockfile: {lock_path}")
    if args.write_runtime_lock:
        write_lockfile(RUNTIME_LOCK, source=RUNTIME_LOCK_SOURCE)
        print(f"Wrote runtime lockfile: {RUNTIME_LOCK}")
    if args.verify_lock:
        lock_path = args.verify_lock if args.verify_lock.is_absolute() else ROOT / args.verify_lock
        verify_hashed_lock(lock_path)
        print(f"Verified hashed lockfile: {lock_path}")
    if not args.write_lock and not args.write_runtime_lock and not args.verify_lock:
        print("Environment check passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
